/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.scene {
	import laya.ui.*;
	import laya.display.*;

	public class GameSceneUI extends Scene {
		public var time_progress_value:Image;
		public var text_time:Text;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("scene/GameScene");

		}

	}
}